import {random,clamp} from './random';
import type {Config,Provider,User,NetworkState,Health} from './types';
export function generate(c:Config):NetworkState{const r=random(c.seed),users:User[]=Array.from({length:c.users},(_,id)=>{let x=r()*20,y=r()*20;if(c.distribution==='clustered'&&r()<.75){const k=Math.floor(r()*3);x=clamp([5,14,9][k]+(r()+r()+r()-1.5)*4,0,20);y=clamp([6,13,16][k]+(r()+r()+r()-1.5)*4,0,20)}if(c.distribution==='underserved'&&r()<.75){x=14+r()*6;y=r()*20}return{id,x,y,demand:.5+r(),assigned:null,quality:0,redundant:false,served:0}});
const bad=new Set(Array.from({length:c.providers},(_,i)=>({i,k:r()})).sort((a,b)=>a.k-b.k).slice(0,Math.round(c.providers*c.malicious/100)).map(x=>x.i));
const providers:Provider[]=Array.from({length:c.providers},(_,id)=>{const scale={sparse:1,medium:.9,dense:.55}[c.density];return{id,actor:id,x:10+(r()*20-10)*scale,y:10+(r()*20-10)*scale,radius:c.radius,capacity:c.capacity,reliability:c.reliability,quality:clamp(c.quality*(.85+r()*.3)),cost:c.cost,stake:c.stake,reputation:.5+r()*.45,malicious:bad.has(id),sybil:false,active:r()<c.reliability,claimed:0,actual:0,served:0,mu:0,redundancy:0,risk:0,attackCost:0,fraud:false}});return{providers,users,health:{utility:0,coverage:0,demand:0,quality:0,redundancy:0,cost:0}}}
export interface Allocation {health:Health;actual:number[];served:number[];redundancy:number[];assignments:number[];service:number[];qualities:number[];overlap:boolean[]}
// Deterministic user order and nearest-quality-first, capacity-constrained allocation.
// Candidate lists are cached for exact leave-one-out reallocations.
export function candidates(ps:Provider[],us:User[]){return us.map(u=>ps.map((p,i)=>({i,d:Math.hypot(p.x-u.x,p.y-u.y)})).filter(v=>ps[v.i].active&&v.d<=ps[v.i].radius).map(v=>({i:v.i,q:ps[v.i].quality*(1-.35*v.d/ps[v.i].radius)})).sort((a,b)=>b.q-a.q||a.i-b.i))}
export function allocate(ps:Provider[],us:User[],c:Config,links= candidates(ps,us),removed=-1):Allocation{const remaining=ps.map(p=>p.capacity),actual=ps.map(()=>0),served=ps.map(()=>0),redundancy=ps.map(()=>0),assignments:number[]=[],service:number[]=[],qualities:number[]=[],overlap:boolean[]=[];let covered=0,demand=0,total=0,quality=0,red=0;
for(let j=0;j<us.length;j++){const u=us[j],ls=links[j];let n=0,best=-1,q=0;for(const v of ls){if(v.i===removed)continue;n++;if(best===-1&&remaining[v.i]>0){best=v.i;q=v.q}}const amount=best<0?0:Math.min(u.demand,remaining[best]);if(n)covered++;if(n>1)red++;if(best>=0){remaining[best]-=amount;actual[best]+=amount;served[best]++;if(n>1)redundancy[best]++}demand+=amount;total+=u.demand;quality+=amount*q;assignments.push(best);service.push(amount);qualities.push(q);overlap.push(n>1)}
const cost=ps.reduce((s,p,i)=>s+(i===removed?0:p.cost),0)/(Math.max(1,c.providers)*10),coverage=covered/Math.max(1,us.length),d=demand/Math.max(1e-12,total),q=quality/Math.max(1e-12,total),redund=red/Math.max(1,us.length),w=c.weights;
return{health:{coverage,demand:d,quality:q,redundancy:redund,cost,utility:w[0]*coverage+w[1]*d+w[2]*q-w[3]*redund-w[4]*cost},actual,served,redundancy,assignments,service,qualities,overlap}}
export function evaluate(net:NetworkState,c:Config){const links=candidates(net.providers,net.users),a=allocate(net.providers,net.users,c,links);net.health=a.health;net.providers.forEach((p,i)=>{p.actual=a.actual[i];p.served=a.served[i];p.redundancy=p.served?a.redundancy[i]/p.served:0;p.mu=p.active?a.health.utility-allocate(net.providers,net.users,c,links,i).health.utility:-c.weights[4]*p.cost/(Math.max(1,c.providers)*10)});net.users.forEach((u,j)=>{u.assigned=a.assignments[j]<0?null:net.providers[a.assignments[j]].id;u.served=a.service[j];u.quality=a.qualities[j];u.redundant=a.overlap[j]});return net}

