import {random,clamp} from './random';
import type {Config,Provider,User,NetworkState,Health} from './types';
export function generate(c:Config):NetworkState{const r=random(c.seed),users:User[]=Array.from({length:c.users},(_,id)=>{let x=r()*20,y=r()*20;if(c.distribution==='clustered'&&r()<.75){const k=Math.floor(r()*3);x=clamp([5,14,9][k]+(r()+r()+r()-1.5)*4,0,20);y=clamp([6,13,16][k]+(r()+r()+r()-1.5)*4,0,20)}if(c.distribution==='underserved'&&r()<.75){x=14+r()*6;y=r()*20}const demand=.5+r();return{id,x,y,demand,baseDemand:demand,assigned:null,quality:0,redundant:false,served:0}});
const bad=new Set(Array.from({length:c.providers},(_,i)=>({i,k:r()})).sort((a,b)=>a.k-b.k).slice(0,Math.round(c.providers*c.malicious/100)).map(x=>x.i));
const providers:Provider[]=Array.from({length:c.providers},(_,id)=>{const scale={sparse:1,medium:.9,dense:.55}[c.density],quality=clamp(c.quality*(.85+r()*.3));return{id,actor:id,x:10+(r()*20-10)*scale,y:10+(r()*20-10)*scale,radius:c.radius,capacity:c.capacity,reliability:c.reliability,quality,baseQuality:quality,cost:c.cost,stake:c.stake,reputation:.5+r()*.45,malicious:bad.has(id),sybil:false,active:r()<c.reliability,participating:true,attacking:false,effort:1,expectedReward:c.pool/Math.max(1,c.providers),lastPayoff:0,cumulativePayoff:0,infrastructureCost:0,claimed:0,actual:0,served:0,mu:0,redundancy:0,risk:0,attackCost:0,fraud:false}});return{providers,users,health:{utility:0,coverage:0,demand:0,quality:0,redundancy:0,cost:0}}}
export interface Allocation {health:Health;actual:number[];served:number[];redundancy:number[];assignments:number[];service:number[];qualities:number[];overlap:boolean[]}
// Deterministic user order and nearest-quality-first, capacity-constrained allocation.
// Candidate lists are cached for exact leave-one-out reallocations.
export interface DistanceLink {i:number;d:number}
export function geometry(ps:Provider[],us:User[]):DistanceLink[][]{
  const cellSize=Math.max(.25,...ps.map(p=>p.radius)),buckets=new Map<string,number[]>(),cell=(v:number)=>Math.floor(v/cellSize),key=(x:number,y:number)=>`${x},${y}`;
  ps.forEach((p,i)=>{const k=key(cell(p.x),cell(p.y)),bucket=buckets.get(k);if(bucket)bucket.push(i);else buckets.set(k,[i])});
  return us.map(u=>{const found:DistanceLink[]=[],cx=cell(u.x),cy=cell(u.y);for(let y=cy-1;y<=cy+1;y++)for(let x=cx-1;x<=cx+1;x++)for(const i of buckets.get(key(x,y))??[]){const p=ps[i],d=Math.hypot(p.x-u.x,p.y-u.y);if(d<=cellSize)found.push({i,d})}return found})
}
export function candidates(ps:Provider[],us:User[],spatial=geometry(ps,us)){return spatial.map(found=>found.filter(({i,d})=>ps[i].active&&d<=ps[i].radius).map(({i,d})=>({i,q:ps[i].quality*(1-.35*d/ps[i].radius)})).sort((a,b)=>b.q-a.q||a.i-b.i))}
export function allocate(ps:Provider[],us:User[],c:Config,links= candidates(ps,us),removed=-1):Allocation{const remaining=ps.map(p=>p.capacity),actual=ps.map(()=>0),served=ps.map(()=>0),redundancy=ps.map(()=>0),assignments:number[]=[],service:number[]=[],qualities:number[]=[],overlap:boolean[]=[];let covered=0,demand=0,total=0,quality=0,red=0;
for(let j=0;j<us.length;j++){const u=us[j],ls=links[j];let n=0,best=-1,q=0;for(const v of ls){if(v.i===removed)continue;n++;if(best===-1&&remaining[v.i]>0){best=v.i;q=v.q}}const amount=best<0?0:Math.min(u.demand,remaining[best]);if(n)covered++;if(n>1)red++;if(best>=0){remaining[best]-=amount;actual[best]+=amount;served[best]++;if(n>1)redundancy[best]++}demand+=amount;total+=u.demand;quality+=amount*q;assignments.push(best);service.push(amount);qualities.push(q);overlap.push(n>1)}
const cost=ps.reduce((s,p,i)=>s+(i===removed||p.participating===false?0:p.cost),0)/(Math.max(1,c.providers)*10),coverage=covered/Math.max(1,us.length),d=demand/Math.max(1e-12,total),q=quality/Math.max(1e-12,total),redund=red/Math.max(1,us.length),w=c.weights;
return{health:{coverage,demand:d,quality:q,redundancy:redund,cost,utility:w[0]*coverage+w[1]*d+w[2]*q-w[3]*redund-w[4]*cost},actual,served,redundancy,assignments,service,qualities,overlap}}
export function evaluate(net:NetworkState,c:Config,exactMarginal=true,spatial?:DistanceLink[][]){const links=candidates(net.providers,net.users,spatial),a=allocate(net.providers,net.users,c,links);net.health=a.health;const totalDemand=net.users.reduce((s,u)=>s+u.demand,0),qualityByProvider=net.providers.map(()=>0),uniqueByProvider=net.providers.map(()=>0);for(let j=0;j<net.users.length;j++){const i=a.assignments[j];if(i>=0){qualityByProvider[i]+=a.service[j]*a.qualities[j];if(!a.overlap[j])uniqueByProvider[i]++}}net.providers.forEach((p,i)=>{p.actual=a.actual[i];p.served=a.served[i];p.redundancy=p.served?a.redundancy[i]/p.served:0;if(exactMarginal)p.mu=p.active?a.health.utility-allocate(net.providers,net.users,c,links,i).health.utility:-c.weights[4]*p.cost/(Math.max(1,c.providers)*10);else p.mu=p.active?c.weights[0]*uniqueByProvider[i]/Math.max(1,net.users.length)+c.weights[1]*p.actual/Math.max(1e-12,totalDemand)+c.weights[2]*qualityByProvider[i]/Math.max(1e-12,totalDemand)-c.weights[3]*a.redundancy[i]/Math.max(1,net.users.length)-c.weights[4]*p.cost/(Math.max(1,c.providers)*10):-c.weights[4]*p.cost/(Math.max(1,c.providers)*10)});net.users.forEach((u,j)=>{u.assigned=a.assignments[j]<0?null:net.providers[a.assignments[j]].id;u.served=a.service[j];u.quality=a.qualities[j];u.redundant=a.overlap[j]});return net}

