export type Attack = 'none'|'false contribution'|'sybil'|'strategic placement'|'fake demand'|'collusion';
export type Mechanism = 'Contribution'|'Quality-adjusted'|'Marginal utility'|'Proposed';
export const mechanisms: Mechanism[]=['Contribution','Quality-adjusted','Marginal utility','Proposed'];
export interface Config {seed:number; providers:number; users:number; malicious:number; radius:number; capacity:number; reliability:number; quality:number; cost:number; stake:number; budget:number; verificationCost:number; sensitivity:number; falsePositive:number; strategy:'risk'|'random'; attack:Attack; inflation:number; attackCost:number; sybils:number; sybilCost:number; fakeDemand:number; collusion:number; density:'sparse'|'medium'|'dense'; distribution:'uniform'|'clustered'|'underserved'; placement:'utility'|'reward'; pool:number; weights:number[]; trials:number}
export const defaults:Config={seed:42,providers:100,users:1000,malicious:20,radius:2.2,capacity:24,reliability:.92,quality:.9,cost:2,stake:10,budget:10,verificationCost:1,sensitivity:.8,falsePositive:.02,strategy:'risk',attack:'false contribution',inflation:3,attackCost:2,sybils:2,sybilCost:3,fakeDemand:25,collusion:.6,density:'medium',distribution:'clustered',placement:'reward',pool:1000,weights:[.3,.35,.25,.06,.04],trials:10};
export interface Provider {id:number; actor:number; x:number;y:number;radius:number;capacity:number;reliability:number;quality:number;cost:number;stake:number;reputation:number;malicious:boolean;sybil:boolean;active:boolean;claimed:number;actual:number;served:number;mu:number;redundancy:number;risk:number;attackCost:number;fraud:boolean}
export interface User {id:number;x:number;y:number;demand:number;assigned:number|null;quality:number;redundant:boolean;served:number}
export interface Health {utility:number;coverage:number;demand:number;quality:number;redundancy:number;cost:number}
export interface NetworkState {providers:Provider[];users:User[];health:Health}
export interface Result {mechanism:Mechanism;rewards:number[];verified:number[];detected:number[];falsePositives:number[];metrics:Record<string,number|null>}
export interface Trial {seed:number;network:NetworkState;results:Result[];config:Config}
