"use client";
import {ResponsiveContainer,BarChart,Bar,XAxis,YAxis,CartesianGrid,Tooltip,Cell,LineChart,Line,Legend} from 'recharts';
import {Table,TableHeader,TableRow,TableHead,TableBody,TableCell} from '@/components/ui/table';
import {mechanisms,type Trial,type Provider} from '@/lib/simulation/types';
import {statistics} from '@/lib/simulation/engine';
import {metricDefinitions,formatMetric as fmt} from '@/lib/simulation/metrics';
export const colors=['#71899a','#a1a1d6','#dbb779','#75dfb9'];
export const mechanismLabel=(mechanism:string)=>mechanism==='Contribution'?'Contribution-based':mechanism;
export function ComparisonChart({trials,metric='leakage',line=false}:{trials:Trial[];metric?:string;line?:boolean}){const data=mechanisms.map((m,i)=>({name:mechanismLabel(m),value:statistics(trials.map(t=>t.results[i].metrics[metric])).mean}));return <div className="chart"><ResponsiveContainer width="100%" height="100%">{line?<LineChart data={trials.map(t=>({seed:t.seed,...Object.fromEntries(t.results.map(r=>[r.mechanism,r.metrics[metric]]))}))} margin={{left:-15,right:20}}><CartesianGrid stroke="#263239" strokeDasharray="3 4"/><XAxis dataKey="seed" tick={{fill:'#93a5a9',fontSize:11}}/><YAxis tick={{fill:'#93a5a9',fontSize:11}}/><Tooltip contentStyle={{background:'#172128',border:'1px solid #32433f'}}/><Legend wrapperStyle={{fontSize:11}}/>{mechanisms.map((m,i)=><Line key={m} dataKey={m} name={mechanismLabel(m)} stroke={colors[i]} strokeWidth={2} dot={{r:3}} connectNulls={false}/>)}</LineChart>:<BarChart data={data} margin={{top:10,right:8,left:-18,bottom:0}}><CartesianGrid stroke="#263239" vertical={false} strokeDasharray="3 4"/><XAxis dataKey="name" tick={{fill:'#96a6ad',fontSize:10}} tickLine={false} axisLine={false}/><YAxis tick={{fill:'#71858e',fontSize:10}} tickLine={false} axisLine={false}/><Tooltip cursor={{fill:'#ffffff05'}} contentStyle={{background:'#1a252b',border:'1px solid #32433f',borderRadius:4,color:'#e0eeee'}} formatter={v=>[fmt(metric,Number(v)),metricDefinitions[metric].label]}/><Bar dataKey="value" radius={[2,2,0,0]} maxBarSize={46}>{data.map((d,i)=><Cell key={d.name} fill={colors[i]}/>)}</Bar></BarChart>}</ResponsiveContainer></div>}
export function RoundChart({trials,metric}:{trials:Trial[];metric:string}){const rounds=Math.max(0,...trials.flatMap(t=>t.results.map(r=>r.history.length))),data=Array.from({length:rounds},(_,round)=>({round:round+1,...Object.fromEntries(mechanisms.map((m,i)=>[m,statistics(trials.map(t=>t.results[i].history[round]?.metrics[metric]??null)).mean]))}));return <div className="round-chart"><ResponsiveContainer width="100%" height="100%"><LineChart data={data} margin={{top:10,right:18,left:-12,bottom:4}}><CartesianGrid stroke="#263239" strokeDasharray="3 4"/><XAxis dataKey="round" tick={{fill:'#7c9094',fontSize:10}} tickLine={false}/><YAxis tick={{fill:'#7c9094',fontSize:10}} tickLine={false}/><Tooltip contentStyle={{background:'#172128',border:'1px solid #32433f',borderRadius:4}} formatter={(v,name)=>[fmt(metric,Number(v)),mechanismLabel(String(name))]} labelFormatter={v=>`Round ${v}`}/><Legend wrapperStyle={{fontSize:10}}/>{mechanisms.map((m,i)=><Line key={m} type="monotone" dataKey={m} name={mechanismLabel(m)} stroke={colors[i]} strokeWidth={2} dot={false} connectNulls/>)}</LineChart></ResponsiveContainer></div>}
export function ProviderTable({trial,result,onSelect}:{trial:Trial;result:Trial['results'][number];onSelect:(p:Provider)=>void}){return <div className="provider-table"><Table><TableHeader><TableRow>{['Provider','Status','Actual / claimed','Marginal utility','Reward','Risk'].map(h=><TableHead key={h}>{h}</TableHead>)}</TableRow></TableHeader><TableBody>{[...trial.network.providers].sort((a,b)=>b.mu-a.mu).map(p=><TableRow key={p.id}><TableCell><button className="text-button" onClick={()=>onSelect(p)}>P{p.id+1} ↗</button></TableCell><TableCell>{p.sybil?'Sybil':p.malicious?'Malicious':'Honest'}</TableCell><TableCell>{p.actual.toFixed(1)} / {p.claimed.toFixed(1)}</TableCell><TableCell>{p.mu.toFixed(5)}</TableCell><TableCell>{result.rewards[trial.network.providers.indexOf(p)].toFixed(2)}</TableCell><TableCell>{(p.risk*100).toFixed(0)}%</TableCell></TableRow>)}</TableBody></Table></div>}
export function ResultsTable({trials}:{trials:Trial[]}){return <section className="panel"><div className="panel-heading"><div><h2>Mechanism evidence</h2><p>Mean · sample standard deviation · 95% confidence interval</p></div><span className="eyebrow">n = {trials.length}</span></div><Table><TableHeader><TableRow><TableHead>Metric</TableHead>{mechanisms.map((m,i)=><TableHead key={m} style={{color:colors[i]}}>{m}</TableHead>)}</TableRow></TableHeader><TableBody>{Object.keys(metricDefinitions).map(k=><TableRow key={k}><TableCell title={metricDefinitions[k].definition}>{metricDefinitions[k].label}</TableCell>{mechanisms.map((m,i)=>{const s=statistics(trials.map(t=>t.results[i].metrics[k]));return <TableCell key={m}><strong>{fmt(k,s.mean)}</strong><small className="stat-sub">SD {fmt(k,s.sd)} · n={s.n}</small><small className="stat-sub">{s.low===null?'CI unavailable':`[${fmt(k,s.low)}, ${fmt(k,s.high)}]`}</small></TableCell>})}</TableRow>)}</TableBody></Table><p className="panel-note">SD and Student-t intervals require at least two defined observations. Missing metrics are excluded individually. Seeds are paired across mechanisms.</p></section>}
