"use client";
import {useState} from 'react';
import {Plus,Minus,RotateCcw} from 'lucide-react';
import type {Trial,Provider,Mechanism} from '@/lib/simulation/types';
export const modes=['Coverage','Marginal Utility','Reward','Fraud Risk','Verification','Network Demand'];
export function NetworkMap({trial,mechanism,mode,onSelect,removed}:{trial:Trial;mechanism:Mechanism;mode:string;onSelect:(p:Provider)=>void;removed?:number}){const [zoom,setZoom]=useState(1);const res=trial.results.find(r=>r.mechanism===mechanism)!,net=res.network??trial.network,ps=net.providers;const maxReward=Math.max(1,...res.rewards),maxMu=Math.max(.0001,...ps.map(p=>p.mu));const color=(p:Provider,i:number)=>mode==='Fraud Risk'?`hsl(${150-p.risk*145} 65% 65%)`:mode==='Verification'?(res.detected.includes(i)?'#ed927f':res.verified.includes(i)?'#8ce5ed':'#586a73'):mode==='Marginal Utility'?(p.mu<0?'#ec997a':`hsl(158 65% ${35+35*p.mu/maxMu}%)`):mode==='Reward'?`hsl(165 65% ${30+45*res.rewards[i]/maxReward}%)`:p.sybil?'#c4a1ee':p.malicious?'#f0a283':'#6fdec0';
return <div className="map-wrap"><svg className="city-map" viewBox="0 0 800 490" role="group" aria-label={`Interactive city network: ${mode}. Select a provider for details.`}><defs><pattern id="city-grid" width="35" height="21.5" patternUnits="userSpaceOnUse"><path d="M35 0H0V21.5" fill="none" stroke="#284039" strokeWidth=".7"/></pattern><clipPath id="bounds"><rect x="50" y="20" width="700" height="430"/></clipPath></defs><rect x="50" y="20" width="700" height="430" fill="#0e1b1b"/><rect x="50" y="20" width="700" height="430" fill="url(#city-grid)"/>{[0,5,10,15,20].map(n=><g key={n} fill="#607d77" fontSize="10" fontFamily="monospace"><text x={50+n*35} y="473" textAnchor="middle">{n}</text><text x="30" y={24+n*21.5}>{n}</text></g>)}<g clipPath="url(#bounds)"><g transform={`translate(${400*(1-zoom)} ${235*(1-zoom)}) scale(${zoom})`}>{mode==='Network Demand'&&Array.from({length:400},(_,i)=>{const x=i%20,y=Math.floor(i/20),n=net.users.filter(u=>Math.floor(u.x)===x&&Math.floor(u.y)===y).length;return n?<rect key={i} x={50+x*35} y={20+y*21.5} width="35" height="21.5" fill="#66dfb6" opacity={Math.min(.8,n/18)}/>:null})}{(mode==='Coverage'||mode==='Marginal Utility')&&ps.filter(p=>p.active).map(p=><ellipse key={`c${p.id}`} cx={50+p.x*35} cy={20+p.y*21.5} rx={p.radius*35} ry={p.radius*21.5} fill={p.malicious?'#dd997008':'#58d4b408'} stroke={p.malicious?'#cc91691e':'#58d4b423'} strokeWidth=".65"/>)}{net.users.map(u=><circle key={`u${u.id}`} cx={50+u.x*35} cy={20+u.y*21.5} r="1.15" fill={u.served?'#729e95':'#52616a'} opacity=".65"/>)}{ps.map((p,i)=><g key={p.id} tabIndex={0} role="button" aria-label={`Inspect provider P${p.id+1}`} onClick={()=>onSelect(p)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();onSelect(p)}}} className={`provider ${p.malicious&&trial.config.attack!=='none'?'attacking':''}`}><title>{`P${p.id+1} · ${p.malicious?"malicious":"honest"} · MU ${p.mu.toFixed(5)}`}</title><circle cx={50+p.x*35} cy={20+p.y*21.5} r="9" fill="transparent"/><circle cx={50+p.x*35} cy={20+p.y*21.5} r={p.sybil?4:3.6} stroke={color(p,i)} strokeWidth="1.4" fill={p.active?color(p,i):'#111c20'}/>{res.verified.includes(i)&&<circle cx={50+p.x*35} cy={20+p.y*21.5} r="6.5" fill="none" stroke="#a0d7dc" strokeWidth=".7"/>}</g>)}</g></g><text x="65" y="43" fill="#77968c" fontFamily="monospace" fontSize="10">SIMULATED CITY / 400 SPATIAL CELLS</text></svg><div className="map-controls"><button aria-label="Zoom in" onClick={()=>setZoom(Math.min(3,zoom+.25))}><Plus size={15}/></button><button aria-label="Zoom out" onClick={()=>setZoom(Math.max(1,zoom-.25))}><Minus size={15}/></button><button aria-label="Reset zoom" onClick={()=>setZoom(1)}><RotateCcw size={14}/></button></div><div className="map-badge"><span className="live-dot"/>{removed===undefined?'FINAL ROUND SNAPSHOT':`PROVIDER P${removed+1} REMOVED`}<span>20 × 20</span></div></div>}


